-- ========================================================
-- KỊCH BẢN KHỞI TẠO CƠ SỞ DỮ LIỆU SUPABASE CHO WEBSITE ABA
-- Hãy sao chép toàn bộ mã SQL dưới đây và dán vào phần 
-- SQL Editor trên Supabase Dashboard của bạn, sau đó nhấn Run.
-- ========================================================

-- 1. Bảng cấu hình chung (Lưu trữ Menu điều hướng động)
CREATE TABLE IF NOT EXISTS public.settings (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Bảng quản lý nội dung các trang dã ngoại (Hero, Objectives, Challenges)
CREATE TABLE IF NOT EXISTS public.pages (
    slug TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    meta_title TEXT,
    meta_description TEXT,
    meta_keywords JSONB, -- Lưu mảng từ khóa dạng JSON
    sections JSONB NOT NULL, -- Lưu cấu trúc banner và chặng trải nghiệm
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Bảng quản lý liên kết rút gọn (Short Links)
CREATE TABLE IF NOT EXISTS public.links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL,
    original_url TEXT NOT NULL,
    description TEXT,
    clicks INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 4. Bảng quản lý mã QR (QR Codes)
CREATE TABLE IF NOT EXISTS public.qrcodes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    value TEXT NOT NULL,
    description TEXT,
    created_at TEXT, -- Lưu chuỗi định dạng ngày giờ Việt Nam
    updated_at TEXT
);

-- 5. Bảng danh sách bài viết/tin tức (Blogs)
CREATE TABLE IF NOT EXISTS public.blogs (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT NOT NULL,
    category TEXT,
    author TEXT,
    image TEXT,
    description TEXT,
    content TEXT,
    views TEXT DEFAULT '0',
    comments_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 6. Bảng thông tin người dùng quản trị (Admin accounts)
CREATE TABLE IF NOT EXISTS public.users (
    username TEXT PRIMARY KEY,
    passcode TEXT NOT NULL,
    name TEXT,
    role TEXT DEFAULT 'admin',
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Thêm một tài khoản quản trị mặc định để đăng nhập
INSERT INTO public.users (username, passcode, name, role)
VALUES ('admin', '123456', 'Administrator', 'admin')
ON CONFLICT (username) DO NOTHING;
